### ISSUE TITLE
Even throwback is broken now

### ISSUE THREAD

**Issue by Junkeira** [Norbyte/bg3se#297]
These last few days some of us could still keep playing the game doing a throwback to before hotfix 18, but today it started to giving errors saying that Script Extender for Game Version 4.47.88.723 doesn't exist.
I know this is not your full-time job, and your probably started this whole project for fun, and didn't expected half a million ppl to download your mod, but it's because of thhis that i ask you, please do a update, there's a lot of ppl depending on you atm.
EDIT: IT'S BACK ON, DISCREDIT THIS POST.

**Comment by RobGreen490** [comment]
Same error even though my game version is 4.1.1.4763283. Trying to figure out where to find my version of the SE to see if maybe it auto updated or something.

**Comment by alterNERDtive** [comment]
SE update will currently auto delete any v13 and v14 script extender you have already present on your machine.

**Comment by Spinnerette** [comment]
My game is version V4.1.1.4494476 (Hotfix 17) and I also just started getting this error. It was working completely fine until I had to close the game for like 30 seconds, but when I tried to launch it again I ran into this problem. The only thing I can think of is that the extender updated itself, or maybe BG3 Mod Manager updated it. I don't know how to check which version of SE I have, or how to stop it from doing this all over again if that really is what happened.

**Comment by XY20130630** [comment]
I make my steam client keep offline, so the game itself does not update. But it is still alerted that Script Extender for Game Version XXX doesn't exist.

**Comment by kanra2** [comment]
I have the same problem.. the workaround stopped working that error made its appearance

**Comment by alterNERDtive** [comment]
> SE update will currently auto delete any v13 and v14 script extender (= for patch 5 and patch 6) you have already present on your machine.

…

**Comment by RobGreen490** [comment]
> SE update will currently auto delete any v13 and v14 script extender (= for patch 5 and patch 6) you have already present on your machine.
> 
> As usual: you better have backups …

Just checked and you were right, I guess the updater deleted all files used by the script extender. Maybe an update is coming?

I found the empty files here in case anyone else wants to check their own.
C:\Users\you\AppData\Local\BG3ScriptExtender\ScriptExtender

**Comment by alterNERDtive** [comment]
![image](https://github.com/Norbyte/bg3se/assets/53827887/fc596440-2651-4a81-aa41-9f501aa74201)

→ should be working again

**Comment by Spinnerette** [comment]
> SE update will currently auto delete any v13 and v14 script extender (= for patch 5 and patch 6) you have already present on your machine.
> 
> As usual: you better have backups …

If you have time, could you please go into a little more detail? So even if my game is on Hotfix 17 and I never updated to Patch 6, Script Extender is just going to update itself and I can never go back to a previous version?
What should we be keeping backups of exactly? I hope these aren't really dumb questions, the "as usual" bit makes me feel like I may have missed something completely obvious.
And, if SE is just going to update itself anyways then do we have to basically disconnect from the internet anytime we want to play old versions, provided we actually had said backups?

Sorry I'm relatively new to modding BG3, especially when it comes to the extender. I didn't even have a github account until a few minutes ago so I could start looking for some help with this.

**Comment by Zhaggygodx** [comment]
> ![image](https://private-user-images.githubusercontent.com/53827887/307007668-fc596440-2651-4a81-aa41-9f501aa74201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDgzNTIsIm5iZiI6MTcwODYwODA1MiwicGF0aCI6Ii81MzgyNzg4Ny8zMDcwMDc2NjgtZmM1OTY0NDAtMjY1MS00YTgxLWFhNDEtOWY1MDFhYTc0MjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEzMjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZTAzOWU2ODc1NWZlNDQ0YzM5ZDk2MTE1MjFkYjQ5YmEwODQ0ZTMwNGY4ZTA0YTlmNmVhNWE0OGM5ZWIyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m_W6AJREKrkyjU6SvY5ymS69EgVlEPbuCuC8LWtArSk)
> 
> → should be working again

Man I feel like such a crackhead. I've been looking for workarounds for hours, read your comment and instantly ran the game. Seeing that beautiful debug console prompt gave me a nice dopamine hit lol

**Comment by kanra2** [comment]
how?

did you re-download it?

**Comment by Spinnerette** [comment]
> ![image](https://private-user-images.githubusercontent.com/53827887/307007668-fc596440-2651-4a81-aa41-9f501aa74201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDg0NDEsIm5iZiI6MTcwODYwODE0MSwicGF0aCI6Ii81MzgyNzg4Ny8zMDcwMDc2NjgtZmM1OTY0NDAtMjY1MS00YTgxLWFhNDEtOWY1MDFhYTc0MjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEzMjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YTNhNzE4YjQ4MGUzMjNjMzJjMWQyZjg5ZTI3YmFkMDQ2NzZkZmI5Y2UwNGIwZWZlNWVmNDk0NmEyYjRiM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.so-ZJBiC1D2dnOooZHuTxt0mY8KYCMR1KFPokASZwNE)
> 
> → should be working again

So it is! Thank you for letting us know!
Though, I still don't know why it broke in the first place. Does SE require a connection to a host or something that I wasn't aware of?

**Comment by alterNERDtive** [comment]
> If you have time, could you please go into a little more detail?

Script extender is a 2-stage affair: you have the `DWrite.dll` that hooks into the game, which checks the game version and then downloads the correct version of SE to use with said version.

It looks like earlier today Norbyte intentionally disabled updates (I assume to protest the state of hotfix 18, but you’d have to ask him). That apparently *un*inentionally, due to 
![image](https://github.com/Norbyte/bg3se/assets/53827887/fcec936f-1e71-44bd-9b98-0beb29cb8f71)
lead to the updater routine deleting the versions it was trying to pull updates for from the local download cache, leaving you without SE for the game you were trying to run.

> So even if my game is on Hotfix 17 and I never updated to Patch 6, Script Extender is just going to update itself and I can never go back to a previous version?

SE will automatically download & run the latest version for the version of the game you are running.

> What should we be keeping backups of exactly?

In general? Your entire system.

> And, if SE is just going to update itself anyways then do we have to basically disconnect from the internet anytime we want to play old versions, provided we actually had said backups?

No, see the long text above.

> Sorry I'm relatively new to modding BG3, especially when it comes to the extender. I didn't even have a github account until a few minutes ago so I could start looking for some help with this.

NP, asking questions is a good thing.

**Comment by Zhaggygodx** [comment]
> how?
> 
> did you re-download it?

I just ran the game as usual. Didn't commit to any workarounds besides rolling back to pre-hotfix #18.

**Comment by Spinnerette** [comment]
> NP, asking questions is a good thing.

Thanks for taking the time to explain things to me (and anyone else that reads all this with the same questions). Getting into modding has taught me to first figure out why something stopped working so I can prevent it from happening again, and _then_ try to find solutions.

**Comment by alterNERDtive** [comment]
> ok I managed to enter the game and it says again version 14 but my bg3 mm still says that I'm missing the SE tho

BG3MM **always** says I’m missing SE for me. Even if I use it to download the thing.

**Comment by dajolieasya** [comment]
Just launch the game. Game client will show SE 14 loaded, and then BG3MM will recognize it too. Had the same issue, everything works.

**Comment by cocoonbug** [comment]
> > how?
> > did you re-download it?
> 
> I just ran the game as usual. Didn't commit to any workarounds besides rolling back to pre-hotfix #18.

i did the rollback workaround too, just replacing bin data--did you have to delete anything or anything like that to get it going again? i verified my files and it seems to work, but i wanted to make sure i'm not somehow making things worse for myself down the line or missing some crucial step to get it all back up-to-date.

**Comment by Norbyte** [comment]
This was a hotfix 18 specific issue that has since been rectified.
