### ISSUE TITLE
versions

### ISSUE THREAD

**Issue by GElVC** [Norbyte/bg3se#96]
where can I get v5 for the mod, if only v3 is downloaded

**Comment by BelegCufea** [comment]
@GElVC 
If you mean the download from [this](https://github.com/Norbyte/bg3se/releases/tag/updater-v3) location. It is an Updater (and yes latest version of it is indeed 3). It should automatically download and install latest version for Script Extender.
If you downloaded the console version you should see Script Extender version on the first line of the Debug console window. Something like `BG3Ext v6 built on Oct 1 2023 08:58:23` meaning you have version 6 of Script Extender.

**Comment by FeistyTeacup** [comment]
> @GElVC If you mean the download from [this](https://github.com/Norbyte/bg3se/releases/tag/updater-v3) location. It is an Updater (and yes latest version of it is indeed 3). It should automatically download and install latest version for Script Extender. If you downloaded the console version you should see Script Extender version on the first line of the Debug console window. Something like `BG3Ext v6 built on Oct 1 2023 08:58:23` meaning you have version 6 of Script Extender.


I was also looking for v5 so I followed what you said and the top of the console says v7. I downloaded the v3 updater, but BG3 Mod Manager says I only have v1 installed and it's the reason 2 of my mods are throwing fits at me. 

I am very confused about all of these versions. Is there somewhere I go to understand better what is happening with the version mismatch?

**Comment by FeistyTeacup** [comment]
@BelegCufea You're a doll, and I feel a little dumb about how I (I think) fixed it; bear with me because I have ADHD which comes with issues summarizing lol

Under the tools category at the top of BG3MM, there is an option for BG3MM to download and install Script Extender for you. This morning I moved everything over to the inactive column saved the new load order without them, and redownloaded Script Extender through BGMM which seemed to have fixed the (!) that the problem mods were throwing and I was able to load BG3 without it crashing on the initial loading screen.  

Listing the ones I had problems with in case someone else is having the same issues:

5e spells was the main one, and the other (Daughter of Loth-good path) I downloaded to match mods in a multiplayer playthrough and don't know much about. 

This morning a couple more mods were mad at the version issue and would just crash the game upon loading until I removed them specifically, and everything worked again; Swarmkeeper subclass for Ranger and Tutorial Chest Summoning.

I'm new to mods so the Tools thing may be widely known, but maybe it will also help someone else lol

**Comment by FeistyTeacup** [comment]
I appreciate your offer and willingness to help. The main one with the issue is 5e spells. 

I had to delete a comment where I thought I fixed my issues (after more of them threw fits), but now upon hitting Launch it automatically says BG3.exe has stopped responding. Even though it loads, it does not any save data. 

It worked this morning before taking my son to school, but now it doesn't. There may be a deeper issue here, but I am too new to mods to understand, so I just removed my mods and I will try again later after I cry from Act3 lol

**Comment by BelegCufea** [comment]
@FeistyTeacup 
I don't use that particular mod, but I have found that other users have a problem with [1.1.24](https://forum.nexusmods.com/index.php?showtopic=9317583/#entry129035922) and [1.1.25](https://forum.nexusmods.com/index.php?showtopic=9317583/#entry129039819) versions.
Try to revert to 1.1.23. It may help.

**Comment by konstantinavalentina** [comment]
I think I'm having problems updating BG3SE.
If I try the download + Extract option from BG3MM the console window tells me there's error and can't reach server.

I'm on version 5 of SE now I think?  That's what it says at top of console when I launch game.  
I think BG3SE is trying to update from https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json ... sooo, if that's correct, can I copy/paste all the things from https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json somewhere to do a manual update?  
I tried doing search for Manifest.json at root drive level and include all subfolders but I can't seem to find a file named that?
I also try manually looking in the BG3 game install folder and also the app data folders but found nothing that way either.

I don't know what I'm doing, and am making guesses trying to fix the update problem just from experience with problem mods and things in past with other games.  

Thanks!

**Comment by BelegCufea** [comment]
@konstantinavalentina 
The Updater (the `DWrite.dll` file you downloaded form [here](https://github.com/Norbyte/bg3se/releases)) will install/update Script Extender into `%AppData%/Local/BG3ScriptExtender` (Win10) or `%LocalAppData%/BG3ScriptExtender`. Try to check there.

As for inability for Updater to reach the server, it is a known issue (not yet resolved). Norbyte (creator of Script Extender) suggests to avoid running BG3 as different user (even Administrator).

As for now, there is no supported way to install Script Extender manualy.
I have uploded [current (v7)](https://www.mediafire.com/file/bfkllmqbwu0gieb/BG3ScriptExtender.zip/file) version on mediafire, so you can try to unzip those files into above mentioned folder.

Best of luck.

**Comment by konstantinavalentina** [comment]
@BelegCufea
Thank you.  I will try that.  :)

**Comment by Norbyte** [comment]
Actually, there is a manual install version available:
https://bg3se-updates.norbyte.dev/Channels/Release/ManualInstall.zip

**Comment by konstantinavalentina** [comment]
@Norbyte - is that manual install link kept current or is that only for v7?   Asking since we now have patch 4 on game, and I get the failure to connect error from the BGSE updater.   I tried using the link and I don't get any red text in the console, but there's some wonky stuff going on with game and I wanted to rule out if I was doing wrong with script extender or if the wonky weird stuff is something wrong in my super long load list of mods.  Thx!  :)
